# Docker Compose file for Vapor
#
# Install Docker on your system to run and test
# your Vapor app in a production-like environment.
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker-compose build
#   Start app: docker-compose up app
#   Stop all: docker-compose down
#
version: '3.7'
volumes:
  db_data:
#3
x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_HOST: db
  DATABASE_NAME: tutoreasymanage
  DATABASE_USERNAME: tutor_easy
  DATABASE_PASSWORD: Gaolei123!
services:
  app:
#6
    image: tutor-easy-manage:latest
    # Configure a bind mount to the directory where course files are stored. 
    volumes:
      - type: bind
        source: ../Courses
        target: /Courses
    build:
      context: . 
    environment:
      <<: *shared_environment
    depends_on:
      - db 
    ports:
      - '8080:8080'
  # 11
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
# 13
  db:
    image: postgres:12-alpine
# 14
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
# 15
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: tutor_easy
      POSTGRES_PASSWORD: Gaolei123!
      POSTGRES_DB: tutoreasymanage
    ports:
      - '5432:5432'
