# Docker Compose file for Vapor
#
# Install Docker on your system to run and test
# your Vapor app in a production-like environment.
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker-compose build
#   Start app: docker-compose up app
#   Stop all: docker-compose down
#
#   docker-compose down will remove containers, next time when docker-compose up, containers will be back as long as images are there. DO NOT prune on volume with -a option when containers are down, otherwise database will be lost!
#
version: '3.7'
volumes:
  db_data:
#3
x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_HOST: db
  DATABASE_NAME: tutoreasymanage
  DATABASE_USERNAME: tutor_easy
  DATABASE_PASSWORD: Gaolei123!
  LC_ALL: zh_CN.UTF-8
services:
  app:
#6
    image: tutor-easy-manage:latest
    # Configure a bind mount to the directory where course files are stored. 
    volumes:
      - type: bind
        source: ../Courses
        target: /Courses
    build:
      context: . 
    environment:
      <<: *shared_environment
    depends_on:
      - db 
    ports:
      - '8080:8080'
  # 11
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
# 13
  db:
    image: postgres:12-alpine
# 14
    volumes:
      - db_data:/tutoreasymanagenew/psql_db
# 15
    environment:
      # PGDATA will be the path where db files reside in the db container, this should be set to the same value as in volume's db_data. Since we set it as an volume, db container will create a volume when first start up, check `docker volume ls` can see that, volume's name should be <service_name>_<volume_name>, which in our case is tutoreasymanage_db_data. Outside the container itself, where does the db file actually lives in the host???
      PGDATA: /tutoreasymanagenew/psql_db
      POSTGRES_USER: tutor_easy
      POSTGRES_PASSWORD: Gaolei123!
      POSTGRES_DB: tutoreasymanage
    ports:
      - '5432:5432'
